CREATE TABLE `job_board`.`job`(
    `id` INT(20) NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `company` VARCHAR(255) NOT NULL,
    `location` VARCHAR(255) NOT NULL,
    `salary` VARCHAR(255) NOT NULL,
    `description` VARCHAR(1000) NOT NULL,
    `isDeleted` BOOLEAN NOT NULL DEFAULT FALSE,
    `isActive` BOOLEAN NOT NULL DEFAULT TRUE,
    `createdAt` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,,
    `updatedAt` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,,
    PRIMARY KEY(`id`)
) ENGINE = INNODB;